name: webview_all
description: a webview widget with full-platform support, based on the existing packages
version: 0.3.7
homepage: https://github.com/moluopro/webview_all

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: '>=2.17.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2
  flutter_web_plugins:
    sdk: flutter
  webview_flutter_web: ^0.2.2+1
  webview_flutter_platform_interface: ^2.4.0
  webf: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
